# Generated by Django 3.0.7 on 2020-07-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='imageboard/post_images/'),
        ),
    ]
